#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.

number_one = 0
number_two = 1
temp = 0
total = 0

while(number_two < 4000000):
    temp = number_two
    number_two = number_one + number_two
    number_one = temp
    
    if number_two%2 == 0:
        total = total + number_two

print(total)
